-- TRIGGER START --------- INSERT END ----------

-- 유저 가입시 유저권한주기
DELIMITER $$
CREATE TRIGGER `USER_INSERT_TRIGGER`
AFTER INSERT ON `USER`
FOR EACH ROW 
BEGIN
INSERT INTO `ROLE_MEMBER` 
SET 
`AUTHORITY` = 'ROLE_USER',  
`ID` = NEW.`ID`;
END $$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER `USER_DELETE_TRIGGER`
AFTER DELETE ON `ROLE_MEMBER`
FOR EACH ROW 
BEGIN
DELETE
FROM `USER` 
WHERE `ID` = OLD.`ID`;
END $$
DELIMITER ;

-- 유저 가입시 default group 추가하기
DELIMITER $$
CREATE TRIGGER `DEFAULT_GROUP_TRIGGER`
AFTER INSERT ON `USER`
FOR EACH ROW 
BEGIN
INSERT INTO `GROUP` 
SET 
`GROUP_NAME` = 'Personal',  
`ID` = NEW.`ID`;
END $$
DELIMITER ;


-- 댓글 등록시 칸반카드 테이블에 댓글 갯수 자동 증가시키기
DELIMITER $$
CREATE TRIGGER `CARD_COMMENT_COUNT_TRIGGER`
AFTER INSERT ON `board_comment`
FOR EACH ROW 
BEGIN
	IF (NEW.`CARD_NO` > 0) THEN
		UPDATE `KANBAN_CARD`
		SET `COMMENT_COUNT` = `COMMENT_COUNT`+1
		WHERE `CARD_NO` = NEW.`CARD_NO`;
	END IF;
END $$
DELIMITER ;

-- 파일 등록시 칸반카드 테이블에 파일 갯수 자동 증가시키기
DELIMITER $$
CREATE TRIGGER `CARD_FILE_COUNT_TRIGGER`
AFTER INSERT ON `board_file`
FOR EACH ROW 
BEGIN
   IF (NEW.`CARD_NO` > 0) THEN
      UPDATE `KANBAN_CARD`
      SET `FILE_COUNT` = `FILE_COUNT`+1
      WHERE `CARD_NO` = NEW.`CARD_NO`;
   END IF;
END $$
DELIMITER ;

-- 댓글 삭제시 칸반카드 테이블에 댓글 갯수 자동 감소시키기
DELIMITER $$
CREATE TRIGGER `CARD_COMMENT_DELETE_COUNT_TRIGGER`
AFTER delete ON `board_comment`
FOR EACH ROW 
BEGIN
   IF (old.`comment_NO` > 0) THEN
      UPDATE `KANBAN_CARD`
      SET `comment_COUNT` = `comment_COUNT`-1
      WHERE `CARD_NO` = old.`CARD_NO`;
   END IF;
END $$
DELIMITER ;

-- 파일 삭제시 칸반카드 테이블에 파일 갯수 자동 감소시키기
DELIMITER $$
CREATE TRIGGER `CARD_FILE_DELETE_COUNT_TRIGGER`
AFTER delete ON `board_file`
FOR EACH ROW 
BEGIN
   IF (old.`FILE_NO` > 0) THEN
      UPDATE `KANBAN_CARD`
      SET `FILE_COUNT` = `FILE_COUNT`-1
      WHERE `CARD_NO` = old.`CARD_NO`;
   END IF;
END $$
DELIMITER ;


-- 보드 추가시 타임라인 테이블에 로그입력하기
DELIMITER $$
CREATE TRIGGER `INSERT_TIMELINE_TRIGGER`
AFTER INSERT ON `ALL_BOARD_LIST`
FOR EACH ROW 
BEGIN
	INSERT INTO `TIMELINE`
	SET
	`COLUMN_NAME` = 'BOARD',  
	`COLUMN_NO` = NEW.`ALL_BOARD_LIST_NO`,
    `TEAM_NO` = NEW.`TEAM_NO`,
    `HISTORY` = NEW.`NAME`,
    `ID` = NEW.`ID`,
    `DML_NO` = 1;
END $$
DELIMITER ;

-- 트리거가 만들어졌는지 확인
SHOW TRIGGERS;